language: c++
os: linux
sudo: false

# This only exists because of a bug: https://github.com/travis-ci/travis-ci/issues/4681
env:
  matrix:
    - EMPTY_JOB_IN_TRAVIS_CI=1

addons:
  apt:
    packages:
      - clang-3.6
      - libclang-3.6-dev
      - llvm-3.6
      - llvm-3.6-dev
      - clang-3.7
      - clang-3.8
      - g++-4.8
      - g++-4.9
      - g++-5
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise

matrix:
  exclude:
    - env: EMPTY_JOB_IN_TRAVIS_CI=1
  include:
    - env: CLANG_VERSION=3.6 BUILD_TYPE=Release UNIT_TEST=1 SANITIZE=0
    - env: CLANG_VERSION=3.7 BUILD_TYPE=Release UNIT_TEST=1 SANITIZE=0
    - env: CLANG_VERSION=3.8 BUILD_TYPE=Debug UNIT_TEST=0 SANITIZE=Asan
    - env: GCC_VERSION=4.8 BUILD_TYPE=Release UNIT_TEST=1 SANITIZE=0
    - env: GCC_VERSION=4.9 BUILD_TYPE=Release UNIT_TEST=1 SANITIZE=0
    - env: GCC_VERSION=5 BUILD_TYPE=Release UNIT_TEST=1 SANITIZE=0
  allow_failures:
    - env: CLANG_VERSION=3.8 BUILD_TYPE=Debug UNIT_TEST=0 SANITIZE=Asan

before_script:
  - |
    if [[ -n $GCC_VERSION ]] ; then 
      export CXX="g++-${GCC_VERSION}"
      export CC="gcc-${GCC_VERSION}"
    fi
  - |
    if [[ -n $CLANG_VERSION ]] ; then 
      export CXX="clang++-${CLANG_VERSION}"
      export CC="clang-${CLANG_VERSION}"
    fi
  - export BUILD_DIR="build_${CC}_${SANITIZE}"
  - export BIN_DIR="bin_${CC}_${SANITIZE}"
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}

script: 
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DMAKE_TEST=${UNIT_TEST} -DSANITIZE=${SANITIZE} -DLOG_LEVEL=0 -DBINARY_OUTPUT_DIRECTORY=${BIN_DIR} ..
  - make
  - cd ..
  - |
    if [[ $UNIT_TEST -eq 1 ]] ; then 
      ./scripts/unit_tests.sh ${BIN_DIR}
    fi
  - |
    if [[ ! $SANITIZE -eq 0 ]] ; then 
      ./scripts/sanitizer.sh ${SANITIZE} ${BIN_DIR}
    fi

branches:
  only:
    - master
    - devel